### ISSUE TITLE
Too many evals

### ISSUE THREAD

**Issue by blottn** [414owen/LocalScope#1]
Runs N evals when creating N variables

**Comment by 414owen** [comment]
Hmmm, that's completely fair, I think you're probably right that string manipulation will be faster than the nested eval. The O(N) space required to store the generated string probably won't be an issue either, so I'd love to see some benchmarks.

**Comment by blottn** [comment]
Also should it be let or var? Let might be more appropriate seeing  as we don't want them globally, rather just as a local variable.

**Comment by blottn** [comment]
Solved #4 and #5
